#!/bin/bash

set -x

if ! [ -f Dockerfile ]; then
  cat Dockerfile.template | sed -e "s#HOME#${HOME}#g" -e "s/USER/${LOGNAME}/g" -e "s/UID/$(id -u ${USER})/g"
  exit 1
fi

if [ "$DOCKER" = "IN" ]; then
  exec tmux -2
fi

if ! docker images | grep -q oregon; then
  docker build -t oregon .
fi

docker run -e DOCKER=IN -i -t \
  -v ${HOME}:${HOME}:rw \
  -u ${USER} -h oregon -w $(pwd) \
  --entrypoint "./devenv" \
  oregon
