#!/bin/bash

cat Dockerfile.template | sed -e "s#HOME#${HOME}#g" \
                              -e "s#USERNAME#${USER}#g" \
                              -e "s#SHELL#${SHELL}#g" \
                              -e "s#UID#$(id -u ${USER})#g" \
                              > Dockerfile

if ! docker images | grep -q oregon-summer-school; then
  docker build -t oregon-summer-school .
fi

docker run -i -t \
  -v ${HOME}:${HOME}:rw \
  -u ${USER} -h oregon-summer-school -w $(pwd) \
  --entrypoint "/bin/$(basename $(echo $SHELL))" \
  oregon-summer-school
